### ISSUE TITLE
install script errors on copy for logo.png to warp_gui.png

### ISSUE THREAD

**Issue by AtomicRobotMan0101** [mrmoein/warp-cloudflare-gui#14]
warp-cloudflare-gui/install.py chucks an error for copying logo.png to /home/USER/.local/share/icons/warp_gui.png

Creating the file and moving it manually works and the entry to the menu displays the icon.  :)

(BTW, the world _needs_ this project!)

(still haven't made the scripts work yet. Another error is being thrown below, but I'm super tired and will look tomorrow)

> Traceback (most recent call last):
  File "/home/atomo/warp-cloudflare-gui/main.py", line 1, in <module>
    from warp_gui.mainwindow import GUI
  File "/home/atomo/warp-cloudflare-gui/warp_gui/mainwindow.py", line 8, in <module>
    from qtwidgets import AnimatedToggle
ModuleNotFoundError: No module named 'qtwidgets'

**Comment by AtomicRobotMan0101** [comment]
Should have mentioned that my OS is Mint Cinnamon 21. Fairly new install.

**All fixed with the qtwidgets error.**

Perhaps in the doco, or the install script, mention/check for these? I'm not a python dude (yet) and newbies would stumble hard on this.

sudo apt install python3-pip
pip install qtwidgets

Works so far.  

Now to get rid of the doubled-up Zero Trust Icon in the Panel.
